### PR TITLE
#120: Trim key and value, allow empty value in CommandLineIngestorDriver

### LINKED ISSUE #120: Fix inconsistencies between CommandLineIngestorDriver and PropertiesIngestorDriver
Fix inconsistencies:

1. In `CommandLineIngestorDriver` whitespace in key and value is not trimmed, while it is trimmed in `PropertiesIngestorDriver`. E.g. `key1 = value1` will be stored as `key1 ` (with whitespace at end) with `CommandLineIngestorDriver`, but as `key1` in `PropertiesIngestorDriver`. The behavior of `PropertiesIngestorDriver` is the expected one.

2. An empty property, i.e. `some.key=` causes an exception in `CommandLineIngestorDriver`, but is allowed in `PropertiesIngestorDriver`. This is inconsistent. Either it should always cause an exception, or it should be allowed. Probably the behavior of `PropertiesIngestorDriver` should be favoured since it directly uses the behaviour of `Configuration2`. Users familiar with `Configuration2` would find a differing behaviour unexpected.

### PR DESCRIPTION
**Pull request by kevinwallimann**
Closes #120

### CODE REVIEW

File: driver/src/main/scala/za/co/absa/hyperdrive/driver/drivers/CommandLineIngestionDriver.scala [hunk 1]
```diff
@@ -52,10 +53,11 @@ object CommandLineIngestionDriver extends IngestionDriver {
   }
 
   private def setOrThrow(setting: String, configuration: Configuration): Unit = {
-    val settingKeyValue = setting.trim.split("=", 2)
-    if (settingKeyValue.length != 2 || settingKeyValue.exists(_.isEmpty)) {
+    if(!setting.contains(PropertyDelimiter)) {
       throw new IllegalArgumentException(s"Invalid setting format: $setting")
+    } else {
+      val settingKeyValue = setting.split(PropertyDelimiter, 2)
+      configuration.setProperty(settingKeyValue(0).trim, settingKeyValue(1).trim)
```
Comment (jozefbakus) [inline driver/src/main/scala/za/co/absa/hyperdrive/driver/drivers/CommandLineIngestionDriver.scala:60]: This is bit unsafe. You can use try and then make sure they are both defined, and catch problems with undefined.

Comment (kevinwallimann) [reply driver/src/main/scala/za/co/absa/hyperdrive/driver/drivers/CommandLineIngestionDriver.scala:60]: Hmm, do you have an example when it could throw? Imo, they will always be defined because `setting` always contains the `PropertyDelimiter` if it is in this branch

Comment (jozefbakus) [reply driver/src/main/scala/za/co/absa/hyperdrive/driver/drivers/CommandLineIngestionDriver.scala:60]: ok
